sudo: required
services:
  - docker
before_install:
  - docker build -t mh10445/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true mh10445/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-167736078466"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secure: "$AWS_SECRET_KEY"